# python imports
import os
from dotenv import load_dotenv, find_dotenv

# local imports
from spot.api import SpotifyApi
from spot.album import SpotifyAlbum

# Load environment variables from .env file
load_dotenv(find_dotenv(), override=True)

CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")

# auth
api = SpotifyApi(client_id=CLIENT_ID, client_secret=CLIENT_SECRET)
token_data = api.login()

# NOTE: this is where you would save the token_data to a file or database

album_api = SpotifyAlbum(api)

# Multiple albums
ids = [
    "2S7LjOBbcZZe1qPCrUekuY",
    "2A3q6lntyhqEBWgxSUICrq",
    "1T9iynoVdpSyy1qIn7jLgg",
]  # Say It, Time to Go, ASMR Love Letters
albums = album_api.get_multiple(ids)

for album in albums["albums"]:
    print(album)


res = {
    "album_type": "single",
    "total_tracks": 1,
    "available_markets": [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "PR",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
    ],
    "external_urls": {
        "spotify": "https://open.spotify.com/album/2S7LjOBbcZZe1qPCrUekuY"
    },
    "href": "https://api.spotify.com/v1/albums/2S7LjOBbcZZe1qPCrUekuY",
    "id": "2S7LjOBbcZZe1qPCrUekuY",
    "images": [
        {
            "url": "https://i.scdn.co/image/ab67616d0000b2738d91fdf94d11971752890de6",
            "height": 640,
            "width": 640,
        },
        {
            "url": "https://i.scdn.co/image/ab67616d00001e028d91fdf94d11971752890de6",
            "height": 300,
            "width": 300,
        },
        {
            "url": "https://i.scdn.co/image/ab67616d000048518d91fdf94d11971752890de6",
            "height": 64,
            "width": 64,
        },
    ],
    "name": "Say It",
    "release_date": "2025-03-10",
    "release_date_precision": "day",
    "type": "album",
    "uri": "spotify:album:2S7LjOBbcZZe1qPCrUekuY",
    "artists": [
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
            },
            "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
            "id": "5rar25ejTh6Z3bZ2MhiAfS",
            "name": "lindsay",
            "type": "artist",
            "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
        }
    ],
    "tracks": {
        "href": "https://api.spotify.com/v1/albums/2S7LjOBbcZZe1qPCrUekuY/tracks?offset=0&limit=50",
        "limit": 50,
        "next": None,
        "offset": 0,
        "previous": None,
        "total": 1,
        "items": [
            {
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
                        },
                        "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
                        "id": "5rar25ejTh6Z3bZ2MhiAfS",
                        "name": "lindsay",
                        "type": "artist",
                        "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
                    }
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "PR",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "disc_number": 1,
                "duration_ms": 252555,
                "explicit": False,
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/0nNDLjah0PaOFn2j7sMsF0"
                },
                "href": "https://api.spotify.com/v1/tracks/0nNDLjah0PaOFn2j7sMsF0",
                "id": "0nNDLjah0PaOFn2j7sMsF0",
                "name": "Say It",
                "preview_url": None,
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:0nNDLjah0PaOFn2j7sMsF0",
                "is_local": False,
            }
        ],
    },
    "copyrights": [
        {"text": "2025 lindsay distributed by Community Music", "type": "C"},
        {"text": "2025 lindsay distributed by Community Music", "type": "P"},
    ],
    "external_ids": {"upc": "8721253684145"},
    "genres": [],
    "label": "Community Music",
    "popularity": 19,
}
res_again = {
    "album_type": "single",
    "total_tracks": 1,
    "available_markets": [],
    "external_urls": {
        "spotify": "https://open.spotify.com/album/2A3q6lntyhqEBWgxSUICrq"
    },
    "href": "https://api.spotify.com/v1/albums/2A3q6lntyhqEBWgxSUICrq",
    "id": "2A3q6lntyhqEBWgxSUICrq",
    "images": [
        {
            "url": "https://i.scdn.co/image/ab67616d0000b273cb55f6446838a90f27f6e17c",
            "height": 640,
            "width": 640,
        },
        {
            "url": "https://i.scdn.co/image/ab67616d00001e02cb55f6446838a90f27f6e17c",
            "height": 300,
            "width": 300,
        },
        {
            "url": "https://i.scdn.co/image/ab67616d00004851cb55f6446838a90f27f6e17c",
            "height": 64,
            "width": 64,
        },
    ],
    "name": "Time to Go",
    "release_date": "2020-01-22",
    "release_date_precision": "day",
    "type": "album",
    "uri": "spotify:album:2A3q6lntyhqEBWgxSUICrq",
    "artists": [
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
            },
            "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
            "id": "5rar25ejTh6Z3bZ2MhiAfS",
            "name": "lindsay",
            "type": "artist",
            "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
        }
    ],
    "tracks": {
        "href": "https://api.spotify.com/v1/albums/2A3q6lntyhqEBWgxSUICrq/tracks?offset=0&limit=50",
        "limit": 50,
        "next": None,
        "offset": 0,
        "previous": None,
        "total": 1,
        "items": [
            {
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
                        },
                        "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
                        "id": "5rar25ejTh6Z3bZ2MhiAfS",
                        "name": "lindsay",
                        "type": "artist",
                        "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/0g6VRF5TU1BM5FvK0yKyS2"
                        },
                        "href": "https://api.spotify.com/v1/artists/0g6VRF5TU1BM5FvK0yKyS2",
                        "id": "0g6VRF5TU1BM5FvK0yKyS2",
                        "name": "French For Rabbits",
                        "type": "artist",
                        "uri": "spotify:artist:0g6VRF5TU1BM5FvK0yKyS2",
                    },
                ],
                "available_markets": [],
                "disc_number": 1,
                "duration_ms": 225882,
                "explicit": False,
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/33FitkhrCvuUFtlvgfzNqb"
                },
                "href": "https://api.spotify.com/v1/tracks/7933VjnlxYm4Rvq8jZXiI1",
                "id": "7933VjnlxYm4Rvq8jZXiI1",
                "linked_from": {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/track/33FitkhrCvuUFtlvgfzNqb"
                    },
                    "href": "https://api.spotify.com/v1/tracks/33FitkhrCvuUFtlvgfzNqb",
                    "id": "33FitkhrCvuUFtlvgfzNqb",
                    "type": "track",
                    "uri": "spotify:track:33FitkhrCvuUFtlvgfzNqb",
                },
                "name": "Time to Go",
                "preview_url": None,
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:7933VjnlxYm4Rvq8jZXiI1",
                "is_local": False,
            }
        ],
    },
    "copyrights": [
        {"text": "2020 lindsay music", "type": "C"},
        {"text": "2020 lindsay music", "type": "P"},
    ],
    "external_ids": {"upc": "859736534910"},
    "genres": [],
    "label": "lindsay music",
    "popularity": 0,
}
res3 = {
    "album_type": "single",
    "total_tracks": 5,
    "available_markets": [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "PR",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
    ],
    "external_urls": {
        "spotify": "https://open.spotify.com/album/1T9iynoVdpSyy1qIn7jLgg"
    },
    "href": "https://api.spotify.com/v1/albums/1T9iynoVdpSyy1qIn7jLgg",
    "id": "1T9iynoVdpSyy1qIn7jLgg",
    "images": [
        {
            "url": "https://i.scdn.co/image/ab67616d0000b273b0c2868a65f281c925036b4b",
            "height": 640,
            "width": 640,
        },
        {
            "url": "https://i.scdn.co/image/ab67616d00001e02b0c2868a65f281c925036b4b",
            "height": 300,
            "width": 300,
        },
        {
            "url": "https://i.scdn.co/image/ab67616d00004851b0c2868a65f281c925036b4b",
            "height": 64,
            "width": 64,
        },
    ],
    "name": "ASMR Love Letters",
    "release_date": "2020-04-04",
    "release_date_precision": "day",
    "type": "album",
    "uri": "spotify:album:1T9iynoVdpSyy1qIn7jLgg",
    "artists": [
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
            },
            "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
            "id": "5rar25ejTh6Z3bZ2MhiAfS",
            "name": "lindsay",
            "type": "artist",
            "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
        }
    ],
    "tracks": {
        "href": "https://api.spotify.com/v1/albums/1T9iynoVdpSyy1qIn7jLgg/tracks?offset=0&limit=50",
        "limit": 50,
        "next": None,
        "offset": 0,
        "previous": None,
        "total": 5,
        "items": [
            {
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
                        },
                        "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
                        "id": "5rar25ejTh6Z3bZ2MhiAfS",
                        "name": "lindsay",
                        "type": "artist",
                        "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/0g6VRF5TU1BM5FvK0yKyS2"
                        },
                        "href": "https://api.spotify.com/v1/artists/0g6VRF5TU1BM5FvK0yKyS2",
                        "id": "0g6VRF5TU1BM5FvK0yKyS2",
                        "name": "French For Rabbits",
                        "type": "artist",
                        "uri": "spotify:artist:0g6VRF5TU1BM5FvK0yKyS2",
                    },
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "PR",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "disc_number": 1,
                "duration_ms": 220224,
                "explicit": False,
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/5HnFtOfXdCJ6rI6fRKgRPY"
                },
                "href": "https://api.spotify.com/v1/tracks/5HnFtOfXdCJ6rI6fRKgRPY",
                "id": "5HnFtOfXdCJ6rI6fRKgRPY",
                "name": "Time to Go",
                "preview_url": None,
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:5HnFtOfXdCJ6rI6fRKgRPY",
                "is_local": False,
            },
            {
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
                        },
                        "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
                        "id": "5rar25ejTh6Z3bZ2MhiAfS",
                        "name": "lindsay",
                        "type": "artist",
                        "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
                    },
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/4XUmpHj581ooyS5rJuCBJg"
                        },
                        "href": "https://api.spotify.com/v1/artists/4XUmpHj581ooyS5rJuCBJg",
                        "id": "4XUmpHj581ooyS5rJuCBJg",
                        "name": "Asha Jefferies",
                        "type": "artist",
                        "uri": "spotify:artist:4XUmpHj581ooyS5rJuCBJg",
                    },
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "PR",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "disc_number": 1,
                "duration_ms": 181958,
                "explicit": False,
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/1grBdwuG0EwFKYeYD5KgJB"
                },
                "href": "https://api.spotify.com/v1/tracks/1grBdwuG0EwFKYeYD5KgJB",
                "id": "1grBdwuG0EwFKYeYD5KgJB",
                "name": "Rituals",
                "preview_url": None,
                "track_number": 2,
                "type": "track",
                "uri": "spotify:track:1grBdwuG0EwFKYeYD5KgJB",
                "is_local": False,
            },
            {
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
                        },
                        "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
                        "id": "5rar25ejTh6Z3bZ2MhiAfS",
                        "name": "lindsay",
                        "type": "artist",
                        "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
                    }
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "PR",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "disc_number": 1,
                "duration_ms": 188685,
                "explicit": False,
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/4xnaL9ByRIzQUEjBcXa0lW"
                },
                "href": "https://api.spotify.com/v1/tracks/4xnaL9ByRIzQUEjBcXa0lW",
                "id": "4xnaL9ByRIzQUEjBcXa0lW",
                "name": "Iris",
                "preview_url": None,
                "track_number": 3,
                "type": "track",
                "uri": "spotify:track:4xnaL9ByRIzQUEjBcXa0lW",
                "is_local": False,
            },
            {
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
                        },
                        "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
                        "id": "5rar25ejTh6Z3bZ2MhiAfS",
                        "name": "lindsay",
                        "type": "artist",
                        "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
                    }
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "PR",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "disc_number": 1,
                "duration_ms": 198904,
                "explicit": False,
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/6Zgx0LXc1HZsfQBf6Azp58"
                },
                "href": "https://api.spotify.com/v1/tracks/6Zgx0LXc1HZsfQBf6Azp58",
                "id": "6Zgx0LXc1HZsfQBf6Azp58",
                "name": "Strangers",
                "preview_url": None,
                "track_number": 4,
                "type": "track",
                "uri": "spotify:track:6Zgx0LXc1HZsfQBf6Azp58",
                "is_local": False,
            },
            {
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/5rar25ejTh6Z3bZ2MhiAfS"
                        },
                        "href": "https://api.spotify.com/v1/artists/5rar25ejTh6Z3bZ2MhiAfS",
                        "id": "5rar25ejTh6Z3bZ2MhiAfS",
                        "name": "lindsay",
                        "type": "artist",
                        "uri": "spotify:artist:5rar25ejTh6Z3bZ2MhiAfS",
                    }
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "PR",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK",
                ],
                "disc_number": 1,
                "duration_ms": 127482,
                "explicit": False,
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/2BwjVTb5WuqEz3mebsCtxB"
                },
                "href": "https://api.spotify.com/v1/tracks/2BwjVTb5WuqEz3mebsCtxB",
                "id": "2BwjVTb5WuqEz3mebsCtxB",
                "name": "Omeio",
                "preview_url": None,
                "track_number": 5,
                "type": "track",
                "uri": "spotify:track:2BwjVTb5WuqEz3mebsCtxB",
                "is_local": False,
            },
        ],
    },
    "copyrights": [
        {"text": "2020 lindsay distributed by Community Music", "type": "C"},
        {"text": "2020 lindsay distributed by Community Music", "type": "P"},
    ],
    "external_ids": {"upc": "9353450599244"},
    "genres": [],
    "label": "Community Music",
    "popularity": 6,
}
